// <auto-generated />
using System;
using BackEnd.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackEnd.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BackEnd.Models.TabelaJogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataJogo")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaximoTemporada")
                        .HasColumnType("int");

                    b.Property<int>("MinimoTemporada")
                        .HasColumnType("int");

                    b.Property<int>("Placar")
                        .HasColumnType("int");

                    b.Property<int>("QuebraRecordeMaximo")
                        .HasColumnType("int");

                    b.Property<int>("QuebraRecordeMinimo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TabelaJogo");
                });
#pragma warning restore 612, 618
        }
    }
}
